//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBudgetPro.ResourcesFolder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBudgetPro.ResourcesFolder.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount should be larger than 0.
        /// </summary>
        public static string AmountRequired {
            get {
                return ResourceManager.GetString("AmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eBudget Pro - Home.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name can not exceed 70 characters..
        /// </summary>
        public static string CategoryNameError {
            get {
                return ResourceManager.GetString("CategoryNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category type.
        /// </summary>
        public static string CategoryType {
            get {
                return ResourceManager.GetString("CategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string ChooseYourLanguage {
            get {
                return ResourceManager.GetString("ChooseYourLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string CurrencyDisplay {
            get {
                return ResourceManager.GetString("CurrencyDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string EntryDateDisplay {
            get {
                return ResourceManager.GetString("EntryDateDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income / Expense Add and Edit.
        /// </summary>
        public static string IncomeExpenseEntryHeader {
            get {
                return ResourceManager.GetString("IncomeExpenseEntryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In use ?.
        /// </summary>
        public static string InUse {
            get {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string LinkAbout {
            get {
                return ResourceManager.GetString("LinkAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income / Expense Entry.
        /// </summary>
        public static string LinkAddAmount {
            get {
                return ResourceManager.GetString("LinkAddAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string LinkAddCategory {
            get {
                return ResourceManager.GetString("LinkAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string LinkHome {
            get {
                return ResourceManager.GetString("LinkHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm you want to delete selected Row !.
        /// </summary>
        public static string ModalBody {
            get {
                return ResourceManager.GetString("ModalBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ModalBtnCancel {
            get {
                return ResourceManager.GetString("ModalBtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string ModalBtnConfirm {
            get {
                return ResourceManager.GetString("ModalBtnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        public static string ModalTitle {
            get {
                return ResourceManager.GetString("ModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ex. Water bill 2015/05.
        /// </summary>
        public static string PlaceholderAmountDescr {
            get {
                return ResourceManager.GetString("PlaceholderAmountDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add / Edit Category.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is required.
        /// </summary>
        public static string RequiredFieldGeneric {
            get {
                return ResourceManager.GetString("RequiredFieldGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance overall.
        /// </summary>
        public static string TableBalanceSumHeader {
            get {
                return ResourceManager.GetString("TableBalanceSumHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click amount to edit a row.
        /// </summary>
        public static string TableCaptionEdit {
            get {
                return ResourceManager.GetString("TableCaptionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Balance by Currency.
        /// </summary>
        public static string TableCaptionSaldo {
            get {
                return ResourceManager.GetString("TableCaptionSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense overall.
        /// </summary>
        public static string TableExpenseSumHeader {
            get {
                return ResourceManager.GetString("TableExpenseSumHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string TableHeaderAmount {
            get {
                return ResourceManager.GetString("TableHeaderAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string TableHeaderAmountBalance {
            get {
                return ResourceManager.GetString("TableHeaderAmountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string TableHeaderCategory {
            get {
                return ResourceManager.GetString("TableHeaderCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TableHeaderDate {
            get {
                return ResourceManager.GetString("TableHeaderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TableHeaderDelete {
            get {
                return ResourceManager.GetString("TableHeaderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TableHeaderDescription {
            get {
                return ResourceManager.GetString("TableHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year-Month.
        /// </summary>
        public static string TableHeaderMonthYear {
            get {
                return ResourceManager.GetString("TableHeaderMonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income overall.
        /// </summary>
        public static string TableIncomeSumHeader {
            get {
                return ResourceManager.GetString("TableIncomeSumHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string TabNameBalance {
            get {
                return ResourceManager.GetString("TabNameBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart display.
        /// </summary>
        public static string TabNameCharts {
            get {
                return ResourceManager.GetString("TabNameCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string TabNameExpenseList {
            get {
                return ResourceManager.GetString("TabNameExpenseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string TabNameIncomeList {
            get {
                return ResourceManager.GetString("TabNameIncomeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID is missing.
        /// </summary>
        public static string UserIDError {
            get {
                return ResourceManager.GetString("UserIDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string ValidationAmountDisplay {
            get {
                return ResourceManager.GetString("ValidationAmountDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the value.
        /// </summary>
        public static string ValidationAmountRange {
            get {
                return ResourceManager.GetString("ValidationAmountRange", resourceCulture);
            }
        }
    }
}
