// <auto-generated />
namespace EBudget.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class datetime2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetime2));
        
        string IMigrationMetadata.Id
        {
            get { return "201506262042093_datetime2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
