//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_req_resp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetGradoviRequest", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer.Messaging.GradoviService.Get" +
        "")]
    [System.SerializableAttribute()]
    public partial class GetGradoviRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DrzavaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DrzavaId {
            get {
                return this.DrzavaIdField;
            }
            set {
                if ((this.DrzavaIdField.Equals(value) != true)) {
                    this.DrzavaIdField = value;
                    this.RaisePropertyChanged("DrzavaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetGradoviResponse", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer.Messaging.GradoviService.Get" +
        "")]
    [System.SerializableAttribute()]
    public partial class GetGradoviResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<WCF_req_resp.ServiceReference1.Grad> Gradovik__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Gradovi>k__BackingField", IsRequired=true)]
        public System.Collections.Generic.List<WCF_req_resp.ServiceReference1.Grad> Gradovik__BackingField {
            get {
                return this.Gradovik__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Gradovik__BackingFieldField, value) != true)) {
                    this.Gradovik__BackingFieldField = value;
                    this.RaisePropertyChanged("Gradovik__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grad", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer.Models.AdvModel", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Grad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCF_req_resp.ServiceReference1.Drzava DrzavaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DrzavaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDGradField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WCF_req_resp.ServiceReference1.Kupac> KupciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_req_resp.ServiceReference1.Drzava Drzava {
            get {
                return this.DrzavaField;
            }
            set {
                if ((object.ReferenceEquals(this.DrzavaField, value) != true)) {
                    this.DrzavaField = value;
                    this.RaisePropertyChanged("Drzava");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DrzavaID {
            get {
                return this.DrzavaIDField;
            }
            set {
                if ((this.DrzavaIDField.Equals(value) != true)) {
                    this.DrzavaIDField = value;
                    this.RaisePropertyChanged("DrzavaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDGrad {
            get {
                return this.IDGradField;
            }
            set {
                if ((this.IDGradField.Equals(value) != true)) {
                    this.IDGradField = value;
                    this.RaisePropertyChanged("IDGrad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WCF_req_resp.ServiceReference1.Kupac> Kupci {
            get {
                return this.KupciField;
            }
            set {
                if ((object.ReferenceEquals(this.KupciField, value) != true)) {
                    this.KupciField = value;
                    this.RaisePropertyChanged("Kupci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Drzava", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer.Models.AdvModel", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Drzava : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<WCF_req_resp.ServiceReference1.Grad> GradoviField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDDrzavaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<WCF_req_resp.ServiceReference1.Grad> Gradovi {
            get {
                return this.GradoviField;
            }
            set {
                if ((object.ReferenceEquals(this.GradoviField, value) != true)) {
                    this.GradoviField = value;
                    this.RaisePropertyChanged("Gradovi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDDrzava {
            get {
                return this.IDDrzavaField;
            }
            set {
                if ((this.IDDrzavaField.Equals(value) != true)) {
                    this.IDDrzavaField = value;
                    this.RaisePropertyChanged("IDDrzava");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kupac", Namespace="http://schemas.datacontract.org/2004/07/ServiceLayer.Models.AdvModel", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Kupac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDKupacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDKupac {
            get {
                return this.IDKupacField;
            }
            set {
                if ((this.IDKupacField.Equals(value) != true)) {
                    this.IDKupacField = value;
                    this.RaisePropertyChanged("IDKupac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefon {
            get {
                return this.TelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonField, value) != true)) {
                    this.TelefonField = value;
                    this.RaisePropertyChanged("Telefon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAdventureService")]
    public interface IAdventureService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureService/GetData", ReplyAction="http://tempuri.org/IAdventureService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureService/GetData", ReplyAction="http://tempuri.org/IAdventureService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAdventureService/GetDataUsingDataContractResponse")]
        WCF_req_resp.ServiceReference1.CompositeType GetDataUsingDataContract(WCF_req_resp.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAdventureService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WCF_req_resp.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WCF_req_resp.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureService/GetGradovi", ReplyAction="http://tempuri.org/IAdventureService/GetGradoviResponse")]
        WCF_req_resp.ServiceReference1.GetGradoviResponse GetGradovi(WCF_req_resp.ServiceReference1.GetGradoviRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureService/GetGradovi", ReplyAction="http://tempuri.org/IAdventureService/GetGradoviResponse")]
        System.Threading.Tasks.Task<WCF_req_resp.ServiceReference1.GetGradoviResponse> GetGradoviAsync(WCF_req_resp.ServiceReference1.GetGradoviRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureService/GetGradoviEf", ReplyAction="http://tempuri.org/IAdventureService/GetGradoviEfResponse")]
        System.Collections.Generic.List<WCF_req_resp.ServiceReference1.Grad> GetGradoviEf();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdventureService/GetGradoviEf", ReplyAction="http://tempuri.org/IAdventureService/GetGradoviEfResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WCF_req_resp.ServiceReference1.Grad>> GetGradoviEfAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdventureServiceChannel : WCF_req_resp.ServiceReference1.IAdventureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdventureServiceClient : System.ServiceModel.ClientBase<WCF_req_resp.ServiceReference1.IAdventureService>, WCF_req_resp.ServiceReference1.IAdventureService {
        
        public AdventureServiceClient() {
        }
        
        public AdventureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdventureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdventureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdventureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WCF_req_resp.ServiceReference1.CompositeType GetDataUsingDataContract(WCF_req_resp.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WCF_req_resp.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(WCF_req_resp.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public WCF_req_resp.ServiceReference1.GetGradoviResponse GetGradovi(WCF_req_resp.ServiceReference1.GetGradoviRequest request) {
            return base.Channel.GetGradovi(request);
        }
        
        public System.Threading.Tasks.Task<WCF_req_resp.ServiceReference1.GetGradoviResponse> GetGradoviAsync(WCF_req_resp.ServiceReference1.GetGradoviRequest request) {
            return base.Channel.GetGradoviAsync(request);
        }
        
        public System.Collections.Generic.List<WCF_req_resp.ServiceReference1.Grad> GetGradoviEf() {
            return base.Channel.GetGradoviEf();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WCF_req_resp.ServiceReference1.Grad>> GetGradoviEfAsync() {
            return base.Channel.GetGradoviEfAsync();
        }
    }
}
