//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Klijent_Ajax_Test.AdvWorksServRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grad", Namespace="http://schemas.datacontract.org/2004/07/WCFTest.Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Grad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCF_Klijent_Ajax_Test.AdvWorksServRef.Drzava DrzavaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DrzavaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDGradField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Klijent_Ajax_Test.AdvWorksServRef.Drzava Drzava {
            get {
                return this.DrzavaField;
            }
            set {
                if ((object.ReferenceEquals(this.DrzavaField, value) != true)) {
                    this.DrzavaField = value;
                    this.RaisePropertyChanged("Drzava");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DrzavaID {
            get {
                return this.DrzavaIDField;
            }
            set {
                if ((this.DrzavaIDField.Equals(value) != true)) {
                    this.DrzavaIDField = value;
                    this.RaisePropertyChanged("DrzavaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDGrad {
            get {
                return this.IDGradField;
            }
            set {
                if ((this.IDGradField.Equals(value) != true)) {
                    this.IDGradField = value;
                    this.RaisePropertyChanged("IDGrad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Drzava", Namespace="http://schemas.datacontract.org/2004/07/WCFTest.Model", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Drzava : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCF_Klijent_Ajax_Test.AdvWorksServRef.Grad[] GradoviField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDDrzavaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Klijent_Ajax_Test.AdvWorksServRef.Grad[] Gradovi {
            get {
                return this.GradoviField;
            }
            set {
                if ((object.ReferenceEquals(this.GradoviField, value) != true)) {
                    this.GradoviField = value;
                    this.RaisePropertyChanged("Gradovi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDDrzava {
            get {
                return this.IDDrzavaField;
            }
            set {
                if ((this.IDDrzavaField.Equals(value) != true)) {
                    this.IDDrzavaField = value;
                    this.RaisePropertyChanged("IDDrzava");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdvWorksServRef.IServiceAdventureWorks")]
    public interface IServiceAdventureWorks {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdventureWorks/GetGradovi", ReplyAction="http://tempuri.org/IServiceAdventureWorks/GetGradoviResponse")]
        WCF_Klijent_Ajax_Test.AdvWorksServRef.Grad[] GetGradovi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAdventureWorks/GetGradovi", ReplyAction="http://tempuri.org/IServiceAdventureWorks/GetGradoviResponse")]
        System.Threading.Tasks.Task<WCF_Klijent_Ajax_Test.AdvWorksServRef.Grad[]> GetGradoviAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAdventureWorksChannel : WCF_Klijent_Ajax_Test.AdvWorksServRef.IServiceAdventureWorks, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAdventureWorksClient : System.ServiceModel.ClientBase<WCF_Klijent_Ajax_Test.AdvWorksServRef.IServiceAdventureWorks>, WCF_Klijent_Ajax_Test.AdvWorksServRef.IServiceAdventureWorks {
        
        public ServiceAdventureWorksClient() {
        }
        
        public ServiceAdventureWorksClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAdventureWorksClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAdventureWorksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAdventureWorksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_Klijent_Ajax_Test.AdvWorksServRef.Grad[] GetGradovi() {
            return base.Channel.GetGradovi();
        }
        
        public System.Threading.Tasks.Task<WCF_Klijent_Ajax_Test.AdvWorksServRef.Grad[]> GetGradoviAsync() {
            return base.Channel.GetGradoviAsync();
        }
    }
}
